make_doc:
  stage: build
  image: ubuntu:17.10
  before_script:
   - apt-get update -qq && apt-get install -y -qq cmake git-core wget make \
     cmake libboost-dev libgmp-dev swig gcc gfortran g++ liblapack-dev libatlas-base-dev \
     lp-solve liblpsolve55-dev python3-dev libpython3-dev bash swig doxygen python3-dev python3-pip
  script:
    - "sh CI/make_siconos_doc.sh"
  artifacts:
    paths:
      - docs/build
  only:
  - update_doc

pages:

  image: python:alpine
  script:
  - mv docs/build/html public
  artifacts:
    paths:
    - public
  dependencies:
  - make_doc
  only:
  - update_doc

