#
# this travis config is also used with jenkins
#


sudo: required

services:
  - docker

env:
  - TRAVIS_TASK=siconos_ubuntu_14_04
  - TRAVIS_TASK=siconos_openblas_lapacke
  - TRAVIS_TASK=siconos_with_mumps
  - TRAVIS_TASK=siconos_with_umfpack
  - TRAVIS_TASK=siconos_ubuntu_17_04
  - TRAVIS_TASK=siconos_ubuntu_17_10
  
before_install:
  - CI/before_install.sh

before_script:
  - mkdir -p build
  - cd build

script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task=$TRAVIS_TASK;
    else
      ../CI/driver.py --run --root-dir=..;
    fi
