sudo: required

services:
  - docker

before_install:
  - CI/before_install.sh

before_script:
  - mkdir -p build
  - cd build

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - ../CI/driver.py --run --root-dir=..
