#
# this travis config is also used with jenkins
#
sudo: required

env:
  - TASK=ubuntu_14_04
  - TASK=openblas_lapacke
  - TASK=with_mumps
  - TASK=with_umfpack
  - TASK=ubuntu_17_04
  - TASK=ubuntu_17_10

matrix:
  include:
    env:
      TASK=ubuntu_14_04

  
before_install:
  - CI/before_install.sh

before_script:
  - mkdir -p build
  - cd build

script:
  - if test "$TRAVIS" = true; then
      ../CI/driver.py --run --root-dir=.. --task=siconos_$TASK;
    else
      ../CI/driver.py --run --root-dir=..;
    fi
