#!/bin/bash
#OAR --project siconos
#OAR -l /nodes=1/cpu=2/core=16,walltime=1:00:00
################################################################################
case $1 in
  --env-ok)
    shift;;
  --fast)
    shift
    pwd=`pwd`
    . $pwd/.siconos-guix-profile/etc/profile && $0 --env-ok $@
    ;;
  *)
    case $1 in -x) shift; set -x;; esac
    MYDIR=`dirname $0`
    
    cat>siconos-disks-manifest.scm<<EOF
(specifications->manifest
 '( "siconos" "benchmark" "clang-toolchain"  "valgrind"
    "suitesparse" "eigen" "boost" "fmt" "range-v3"
    "cmake" "ninja" "bash" "coreutils" "which" "python" "python-pip" "python-numpy" 
    "pybind11" "strace" "jupyter" "python-ipykernel" "procps" "gdb" "git" "emacs-next"
    "time" "parallel" "findutils"))
EOF
    cat>siconos-2023-11-08.scm<<EOF
(list (channel
        (name 'guix)
        (url "https://git.savannah.gnu.org/git/guix.git")
        (branch "master")
        (commit
          "461577f0fce1b69a88a752857eeee2e9e1116d6c")
        (introduction
          (make-channel-introduction
            "9edb3f66fd807b096b48283debdcddccfea34bad"
            (openpgp-fingerprint
              "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA"))))
      (channel
        (name 'guix-hpc)
        (url "https://gitlab.inria.fr/bremond/guix-hpc.git")
        (branch "add-siconos")
        (commit
         "f6d6373f6a4542585397178c2ec3e58c4990f0da")))
EOF
    # guix environment setup
    # export PATH=/var/guix/profiles/per-user/root/current-guix/bin:$PATH
    # export GUIX_DAEMON_SOCKET=guix://luke.u-ga.fr
    [ -f /applis/site/guix-start.sh ] && . /applis/site/guix-start.sh
    pwd=`pwd`
    rm -f $pwd/.siconos-guix-profile
#    guix_isolation_args="--container -N --emulate-fhs --share=/tmp --share=$HOME"
    guix_isolation_args="--pure"
    guix_cmd="guix time-machine -C ./siconos-2023-11-08.scm --"
    exec $guix_cmd shell $guix_args \
         --root=.siconos-guix-profile \
         --manifest=siconos-disks-manifest.scm -- $0 --env-ok $@
    ;;
esac
time=`which time`
while [ $# -gt 0 ]; do 
  case $1 in
    --help)
      cat README.md
      exit 0
      ;;
    --install)
      shift
      rm -rf venv
      python3 -m venv --system-site-packages venv
      . venv/bin/activate
      
      pip install --upgrade pip
      venv/bin/pip3 --version
      venv/bin/pip3 install .
      ;;
    --repl)
      shift
      . venv/bin/activate
      export LD_LIBRARY_PATH=`pwd`/venv/lib/python3.9/site-packages/nonos/:$LD_LIBRARY_PATH
      python3
      ;;
    --shell)
      shift
      . venv/bin/activate
      export LD_LIBRARY_PATH=`pwd`/venv/lib/python3.9/site-packages/nonos/:$LD_LIBRARY_PATH
      bash -i
      ;;
    --vview)
      shift
      . venv/bin/activate
      export LD_LIBRARY_PATH=`pwd`/venv/lib/python3.9/site-packages/nonos/:$LD_LIBRARY_PATH
      python3 ./src/siconos/py/nonos/vview.py $@
      ;;
    --vexport)
      shift
      siconos_vexport $@
      ;;
    --export-para)
      shift
      case $1 in --nprocs) shift; nprocs=$1;; *) nprocs=1;; esac
      siconos_vexport --global-filter --gen-para-script=$nprocs $1 > vrun-pprocess
      chmod +x vrun-pprocess
      $time -f '%E %M' ./vrun-pprocess
      ;;
    *)
      script=$1
      shift
      . venv/bin/activate
      export LD_LIBRARY_PATH=`pwd`/venv/lib/python3.9/site-packages/nonos/:$LD_LIBRARY_PATH
      $time -f '%E %M' python3 $script > `basename $script`.log
      ;;
  esac
done
